# Generated by Django 5.2.6 on 2025-09-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('tx_type', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('nameOrig', models.CharField(db_index=True, max_length=64)),
                ('nameDest', models.CharField(db_index=True, max_length=64)),
                ('oldbalanceOrg', models.FloatField(default=0.0)),
                ('newbalanceOrig', models.FloatField(default=0.0)),
                ('oldbalanceDest', models.FloatField(default=0.0)),
                ('newbalanceDest', models.FloatField(default=0.0)),
                ('isFraud', models.BooleanField(default=False)),
                ('isFlaggedFraud', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
